package Calculator;

import java.awt.event.KeyEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gian_
 */
public class Calculator extends javax.swing.JFrame {
    String firstNumber = "",secondNumber = "",operator = "",result = "";
    Operations operations = new Operations();

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JInputLBL = new javax.swing.JLabel();
        JOperationLBL = new javax.swing.JLabel();
        JFourbtn = new javax.swing.JButton();
        JMultibtn = new javax.swing.JButton();
        JFivebtn = new javax.swing.JButton();
        JSumbtn = new javax.swing.JButton();
        JSixbtn = new javax.swing.JButton();
        JOnebtn = new javax.swing.JButton();
        JTwobtn = new javax.swing.JButton();
        JThreebtn = new javax.swing.JButton();
        JDotbtn = new javax.swing.JButton();
        JZerobtn = new javax.swing.JButton();
        JEqualsbtn = new javax.swing.JButton();
        JEightbtn = new javax.swing.JButton();
        JNinebtn = new javax.swing.JButton();
        JSevenbtn = new javax.swing.JButton();
        JSubbtn = new javax.swing.JButton();
        JDivbtn = new javax.swing.JButton();
        JClearAllbtn = new javax.swing.JButton();
        JClearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JInputLBL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JInputLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JInputLBL.setToolTipText("");

        JOperationLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JOperationLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JFourbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JFourbtn.setText("4");
        JFourbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFourbtnActionPerformed(evt);
            }
        });

        JMultibtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JMultibtn.setText("x");
        JMultibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMultibtnActionPerformed(evt);
            }
        });

        JFivebtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JFivebtn.setText("5");
        JFivebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFivebtnActionPerformed(evt);
            }
        });

        JSumbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JSumbtn.setText("+");
        JSumbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSumbtnActionPerformed(evt);
            }
        });

        JSixbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JSixbtn.setText("6");
        JSixbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSixbtnActionPerformed(evt);
            }
        });

        JOnebtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JOnebtn.setText("1");
        JOnebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOnebtnActionPerformed(evt);
            }
        });

        JTwobtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JTwobtn.setText("2");
        JTwobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTwobtnActionPerformed(evt);
            }
        });

        JThreebtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JThreebtn.setText("3");
        JThreebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JThreebtnActionPerformed(evt);
            }
        });

        JDotbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JDotbtn.setText(".");
        JDotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDotbtnActionPerformed(evt);
            }
        });

        JZerobtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JZerobtn.setText("0");
        JZerobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JZerobtnActionPerformed(evt);
            }
        });

        JEqualsbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JEqualsbtn.setText("=");
        JEqualsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEqualsbtnActionPerformed(evt);
            }
        });

        JEightbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JEightbtn.setText("8");
        JEightbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEightbtnActionPerformed(evt);
            }
        });

        JNinebtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JNinebtn.setText("9");
        JNinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNinebtnActionPerformed(evt);
            }
        });

        JSevenbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JSevenbtn.setText("7");
        JSevenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSevenbtnActionPerformed(evt);
            }
        });

        JSubbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JSubbtn.setText("-");
        JSubbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSubbtnActionPerformed(evt);
            }
        });

        JDivbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JDivbtn.setText("/");
        JDivbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDivbtnActionPerformed(evt);
            }
        });

        JClearAllbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JClearAllbtn.setText("CE");
        JClearAllbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClearAllbtnActionPerformed(evt);
            }
        });

        JClearbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JClearbtn.setText("C");
        JClearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JOperationLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JDotbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JZerobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JEqualsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JOnebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTwobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JThreebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JSubbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSumbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(JClearAllbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JClearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JFourbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JFivebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JSixbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JMultibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JSevenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JEightbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JNinebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JDivbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JInputLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JOperationLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JClearAllbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JClearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JEightbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNinebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSevenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDivbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFourbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFivebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSixbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JMultibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JOnebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTwobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JThreebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSubbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDotbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JZerobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JEqualsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSumbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(JInputLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(328, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertCharInInputLabel(String inputUser) {
        this.JInputLBL.setText(this.JInputLBL.getText()+inputUser);
    }
    
    private void insertCharInOperationLabel(boolean result) {
        if (result) {
            this.JOperationLBL.setText(this.JOperationLBL.getText()+ " " + this.secondNumber);
            return;
        }
        this.JOperationLBL.setText(this.firstNumber + " " + this.operator);
        this.JInputLBL.setText("");
    }
    
    private void insertResultInLabel() {
        this.JInputLBL.setText(this.result);
    }
    
    private void clear() {
        this.JInputLBL.setText(this.JInputLBL.getText().substring(0,this.JInputLBL.getText().length()-1));
    }
    
    private void JDivbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDivbtnActionPerformed
        if (this.secondNumber == null || this.secondNumber.isEmpty()) {
            this.operator = "/";
            this.insertCharInOperationLabel(false);
        }
    }//GEN-LAST:event_JDivbtnActionPerformed

    private void JSubbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSubbtnActionPerformed
        if (this.secondNumber == null || this.secondNumber.isEmpty()) {
            this.operator = "-";
            this.insertCharInOperationLabel(false);
        }
    }//GEN-LAST:event_JSubbtnActionPerformed

    private void JSevenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSevenbtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"7";
            this.insertCharInInputLabel("7");
            return;
        }
        this.secondNumber = this.secondNumber+"7";
        this.insertCharInInputLabel("7");
    }//GEN-LAST:event_JSevenbtnActionPerformed

    private void JNinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNinebtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"9";
            this.insertCharInInputLabel("9");
            return;
        }
        this.secondNumber = this.secondNumber+"9";
        this.insertCharInInputLabel("9");
    }//GEN-LAST:event_JNinebtnActionPerformed

    private void JEightbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEightbtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"8";
            this.insertCharInInputLabel("8");
            return;
        }
        this.secondNumber = this.secondNumber+"8";
        this.insertCharInInputLabel("8");
    }//GEN-LAST:event_JEightbtnActionPerformed

    private void JEqualsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEqualsbtnActionPerformed
        if (this.result.length() == 0 && !this.secondNumber.isEmpty()) {
            this.result = this.operations.Operation(firstNumber, secondNumber, operator);
            this.insertCharInOperationLabel(true);
            this.insertResultInLabel();
        }
    }//GEN-LAST:event_JEqualsbtnActionPerformed

    private void JZerobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JZerobtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"0";
            this.insertCharInInputLabel("0");
            return;
        }
        this.secondNumber = this.secondNumber+"0";
        this.insertCharInInputLabel("0");
    }//GEN-LAST:event_JZerobtnActionPerformed

    private void JThreebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JThreebtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"3";
            this.insertCharInInputLabel("3");
            return;
        }
        this.secondNumber = this.secondNumber+"3";
        this.insertCharInInputLabel("3");
    }//GEN-LAST:event_JThreebtnActionPerformed

    private void JTwobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTwobtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"2";
            this.insertCharInInputLabel("2");
            return;
        }
        this.secondNumber = this.secondNumber+"2";
        this.insertCharInInputLabel("2");
    }//GEN-LAST:event_JTwobtnActionPerformed

    private void JOnebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOnebtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"1";
            this.insertCharInInputLabel("1");
            return;
        }
        this.secondNumber = this.secondNumber+"1";
        this.insertCharInInputLabel("1");
    }//GEN-LAST:event_JOnebtnActionPerformed

    private void JSixbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSixbtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"6";
            this.insertCharInInputLabel("6");
            return;
        }
        this.secondNumber = this.secondNumber+"6";
        this.insertCharInInputLabel("6");
    }//GEN-LAST:event_JSixbtnActionPerformed

    private void JSumbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSumbtnActionPerformed
        if (this.secondNumber == null || this.secondNumber.isEmpty()) {
            this.operator = "+";
            this.insertCharInOperationLabel(false);
        }
    }//GEN-LAST:event_JSumbtnActionPerformed

    private void JFivebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFivebtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"5";
            this.insertCharInInputLabel("5");
            return;
        }
        this.secondNumber = this.secondNumber+"5";
        this.insertCharInInputLabel("5");
    }//GEN-LAST:event_JFivebtnActionPerformed

    private void JMultibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMultibtnActionPerformed
        if (this.secondNumber == null || this.secondNumber.isEmpty()) {
            this.operator = "x";
            this.insertCharInOperationLabel(false);
        }
    }//GEN-LAST:event_JMultibtnActionPerformed

    private void JFourbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFourbtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber+"4";
            this.insertCharInInputLabel("4");
            return;
        }
        this.secondNumber = this.secondNumber+"4";
        this.insertCharInInputLabel("4");
    }//GEN-LAST:event_JFourbtnActionPerformed

    private void JDotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDotbtnActionPerformed
        if (this.result.length() > 0) {
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            if (this.firstNumber.contains(".")) {
                return;
            }
            if (this.firstNumber.length() == 0) {
                this.firstNumber = this.firstNumber+"0.";
                this.insertCharInInputLabel("0.");
                return;
            }
            this.firstNumber = this.firstNumber+".";
            this.insertCharInInputLabel(".");
            return;
        }
        if (this.secondNumber.contains(".")) {
                return;
            }
            if (this.secondNumber.length() == 0) {
                this.secondNumber = this.secondNumber+"0.";
                this.insertCharInInputLabel("0.");
                return;
            }
        this.secondNumber = this.secondNumber+".";
        this.insertCharInInputLabel(".");
    }//GEN-LAST:event_JDotbtnActionPerformed

    private void JClearAllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClearAllbtnActionPerformed
        this.result = "";
        this.operator = "";
        this.firstNumber = "";
        this.secondNumber = "";
        this.JInputLBL.setText("");
        this.JOperationLBL.setText("");
    }//GEN-LAST:event_JClearAllbtnActionPerformed

    private void JClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClearbtnActionPerformed
        if (this.JInputLBL.getText().length() == 0){
            return;
        }
        if (this.result.length() > 0) {
            this.JClearAllbtnActionPerformed(evt);
            return;
        }
        if (this.operator == null || this.operator.isEmpty()) {
            this.firstNumber = this.firstNumber.substring(0, this.firstNumber.length()-1);
            this.clear();
            return;
        }
        this.secondNumber = this.secondNumber.substring(0, this.secondNumber.length()-1);
        this.clear();
    }//GEN-LAST:event_JClearbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JClearAllbtn;
    private javax.swing.JButton JClearbtn;
    private javax.swing.JButton JDivbtn;
    private javax.swing.JButton JDotbtn;
    private javax.swing.JButton JEightbtn;
    private javax.swing.JButton JEqualsbtn;
    private javax.swing.JButton JFivebtn;
    private javax.swing.JButton JFourbtn;
    private javax.swing.JLabel JInputLBL;
    private javax.swing.JButton JMultibtn;
    private javax.swing.JButton JNinebtn;
    private javax.swing.JButton JOnebtn;
    private javax.swing.JLabel JOperationLBL;
    private javax.swing.JButton JSevenbtn;
    private javax.swing.JButton JSixbtn;
    private javax.swing.JButton JSubbtn;
    private javax.swing.JButton JSumbtn;
    private javax.swing.JButton JThreebtn;
    private javax.swing.JButton JTwobtn;
    private javax.swing.JButton JZerobtn;
    // End of variables declaration//GEN-END:variables
}
